global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: connect-integration-examples
  regions:
  - us-east-1
  reporting: true
tests:
  defaults:
    parameter_input: defaults.json
    template_file: example.template
