global:
  marketplace-ami: false
  owner: quickstart@amazon.com
  qsname: connect-integration-qualtrak
  regions:
  - us-east-1
  reporting: true
tests:
  amazonconnect:
    parameter_input: evaluate-amazonconnect-json.json
    template_file: evaluate-amazonconnect-json.template
